import {sdrFetch} from './sdrApi';

export type CrmRecentRecord = {id:string;entity:'note'|'activity';sourceUrl:string|null;linkEvidence:Array<{type:'lead'|'deal';id:string;leadId:string}>;eventAt:string|null;sourceUpdatedAt:string;sourceUpdatedField:string;observedAt:string|null;sourceReadStartedAt:string|null;originStatus:'unknown';text:string;textTruncated:boolean;subject:string|null;subjectTruncated:boolean};
export type CrmRecentRecords = {status:'available'|'unavailable';reason:string|null;note:CrmRecentRecord|null;completedCall:CrmRecentRecord|null;email:{status:'unavailable';reason:string};coverage:{notes:{status:string;checkedAt:string|null;errorCategory:string|null};activities:{status:string;checkedAt:string|null;errorCategory:string|null};checkedAt:string;partial:true};asOf:string};
export type CrmFollowUp = {id:string;leadId:string;leadTitle?:string|null;leadLifecycle?:string|null;subject:string|null;type?:string|null;note:string|null;ownerId:string|null;ownerName?:string|null;dueDate:string|null;dueTime:string|null;dueLocalDate?:string|null;dueLocalTime?:string|null;done:boolean;sourceUpdatedAt:string|null;observedAt:string|null;sourceUrl:string|null;recentRecords?:CrmRecentRecords;
leadOwnerId?:string|null;leadOwnerName?:string|null;contactName?:string|null;contactEmail?:string|null;quoteStatus?:'unverified';outreachReviewRequired?:boolean;restrictions?:Array<{id:string;reason:string;providerStopStatus:string}>;lastReply?:{receivedAt:string;intent:string|null;staffResponseAt:string|null}|null;
attention?:{reason:'recent_verified_reply';providerMessageId:string;sourceMessageId:string;threadId:string|null;mailbox:string;receivedAt:string;detectedAt:string;factObservedAt:string;linkEvidence:string}};
export type FollowupReviewProject = {leadId:string;title:string|null;ownerId:string|null;ownerName:string|null;sourceUrl:string|null;latestAt:string;evidence:Array<{id:string;entity:string;text:string;subject:string|null;sourceUpdatedAt:string;observedAt:string;sourceUrl:string|null}>};
export type CrmSnapshot = {entity:string;entity_id:string;data:Record<string,unknown>|null;lifecycle:string;source_updated_at:string|null;observed_at:string|null;source_url:string|null;access_status?:string};
export type CrmHealth = {scopes:Array<{scope:string;status:string;checkedAt?:string|null;completedThrough?:string|null;errorCategory?:string|null}>;inbox:{pending:number;leased:number;dead:number;oldestPendingAt:string|null}|null;observedAt:string};
export type CrmObservations = {lead:CrmSnapshot|null;items:CrmSnapshot[];revisions:Array<{entity:string;entity_id:string;action:string;source_at:string|null;observed_at:string|null;actor_evidence?:{source?:string;execution?:string;ownership?:string;accountId?:string|null}|null;event_id?:string|null;source_read_started_at?:string|null;observation_source_at?:string|null;data:Record<string,unknown>|null;source_url:string|null}>;hasMore?:{items:boolean;revisions:boolean};unavailable?:string|null;freshness:CrmHealth;source:string};
const leadPath=(id:string)=>`/api/sdr/crm/leads/${encodeURIComponent(id)}`;
export const sdrCrmApi={
  followupReview:(query='')=>sdrFetch<{items:FollowupReviewProject[];nextCursor:string|null;freshness:CrmHealth;unavailable?:string|null}>(`/api/sdr/crm/followup-review${query}`),
  users:()=>sdrFetch<{users:Array<{id:string;name:string}>;checkedAt:string}>('/api/sdr/crm/users'),
  followups:(query='')=>sdrFetch<{items:CrmFollowUp[];owners?:Array<{id:string;name:string|null}>;nextCursor:string|null;freshness:CrmHealth;unavailable?:string|null;authorization?:string;replyCoverage?:{status:'partial'|'unknown';eligibleMailboxes:number;visibleMailboxes:number;lastCollectedAt:string|null}}>(`/api/sdr/crm/followups${query}`),
  observations:(id:string)=>sdrFetch<CrmObservations>(`${leadPath(id)}/observations`),
};
