import {ArrowRight,Check,ChevronDown} from 'lucide-react';
import type {WorkspaceView} from './navigation';
const sections:{name:string;route:WorkspaceView;current:string;changes:string[];proposals:string[];preserve:string}[]=[
 {name:'Navigation & native SDR',route:'sdr',current:'SDR opens directly in the shared workspace. Overview was removed.',changes:['The shared header and continuous SDR layout replace the nested frame.','Familiar cold and nurture navigation remains in place.','Legacy overview links open SDR.'],proposals:[],preserve:'Existing document, project and SDR links, permissions and actions remain available.'},
 {name:'Sales reporting',route:'sales',current:'Monthly reporting is available inside the SDR dashboard, mixing company performance with outreach operations.',changes:['A dedicated company Sales page, with count, booked revenue and average sale.','Calendar presets, custom dates and clickable monthly drill-down.','Reuse the tested monthly bars, line and table, with the same test exclusions.','Keep unavailable and partial data visibly distinct from zero.'],proposals:['Add a won-deal detail list so Derek can reconcile any month row by row.','Add previous-period comparison and export after confirming the reporting scope.','Connect collected payments before displaying cash revenue.'],preserve:'The existing SDR reporting dashboard remains available; attribution is not changed.'},
 {name:'Documents',route:'dashboard',current:'The request queue, filters, project detail and generation flow are the team’s existing production tools.',changes:['Documents becomes an explicit top-level work area.','The shared layout gives document staff a clearer route to Archive, Settings and Methodology.','Readable shared context and spacing surround the existing queue.','The overview counts Ready requests separately from Complete; the current queue’s Complete card retains its existing rule.','Mobile document search and status filters have room to use.'],proposals:['Add a filtered “needs review” entry and request-age sorting.','Show the next required step and missing fields before opening a project.','Make generation progress, failure reason and retry eligibility visible together.','Only add state-template selection once Derek confirms the remaining ProSWPPP templates.'],preserve:'Project selection, search, save, generation, archive, bulk actions and forms retain their current behaviour.'},
 {name:'SDR · Dashboard',route:'sdr',current:'The dashboard contains the team’s daily outreach controls, operational checks and reporting.',changes:['It remains in its familiar workspace.','Company Sales also has a direct top-level entry, so Derek can reach it without entering the SDR workflow.'],proposals:['Prioritise the work requiring action today, then team performance.','Let staff collapse low-use analysis while retaining filters and evidence.','Explain held drafts and source freshness alongside each affected action.'],preserve:'The complete SDR component and workspace are unchanged in this local build.'},
 {name:'SDR · Leads & Priority',route:'sdr',current:'Staff inspect leads and engagement signals before deciding whom to contact.',changes:['Existing list, drawer, search and engagement controls are retained.'],proposals:['Show project identity, last contact and next eligible contact date together.','Show CRM status age and verification state so a stale record is easy to recognise.','Label the evidence behind priority signals, including tracking limitations.','Review possible duplicate recipient/project records before offering consolidation.'],preserve:'Existing lead deep links, ownership rules and priority dismiss/seen actions.'},
 {name:'SDR · Queue',route:'sdr',current:'Staff review pending and failed drafts and decide whether to approve, edit or reject.',changes:['The existing queue and draft detail remain in their current locations.'],proposals:['Separate actionable failures from deliberate safety holds.','Show project, recipient, last follow-up and hold reason before any retry.','Group confirmed stale drafts for a review action with an explicit count.','Keep send/retry confirmation tied to the existing CRM and cooldown checks.'],preserve:'No sending, retry, approval or cooldown logic changes are included.'},
 {name:'SDR · Inbox',route:'sdr',current:'The inbox and recent-reply context support thread inspection and follow-up.',changes:['Existing mailbox selection, reply view and connection flow are retained.'],proposals:['Show which mailboxes have complete, partial or disconnected history.','Display classification, sequence stop receipt and CRM-task result per reply.','Show a pending action separately from an action completed successfully.','Validate new live reply effects before claiming the whole feedback loop is complete.'],preserve:'Existing OAuth return route, reply actions and staff permission scope.'},
 {name:'SDR · Mailboxes',route:'sdr',current:'Staff see sender settings, warming state, caps and connection details.',changes:['Existing mailbox settings and connections are retained.'],proposals:['Put connected state, today’s cap, sent count and hold reason on one row.','Explain the difference between an active mailbox and one eligible to send.','Expose last health check and incomplete history without implying delivery.'],preserve:'Daily caps, warmup ramp, signatures and credential handling.'},
 {name:'SDR · Templates & sequences',route:'sdr',current:'Messaging tools cover reusable copy and sequence setup.',changes:['The existing messaging screens remain available.'],proposals:['Show which sequence and step use each template.','Add a readable sequence timeline: delay, channel, stop rule and follow-up receipt.','Detect Apollo/CRM drift through a read-only comparison before offering a sync.','Require evidence before labelling overlapping enrollments as duplicate sends.'],preserve:'Provider sequences, enrollments and templates are not edited by this revamp.'},
 {name:'SDR · Permits & Team',route:'sdr',current:'Permit intake and team/mailbox routing support additional lead sources and staff administration.',changes:['Existing permit and administrator-only Team screens are retained.'],proposals:['Show permit-source freshness, held records and outreach eligibility separately.','Explain mailbox ownership and routing before a staff change is saved.','Show account access and password status without revealing secrets.'],preserve:'Existing roles, permit caps, exports and routing controls.'},
 {name:'SDR · Nurture',route:'sdr',current:'Campaigns, lists, contacts and automations have their own familiar navigation.',changes:['The entire Cold/Nurture lane switch and Nurture navigation stay as they are.'],proposals:['Clarify campaign state, eligible audience and next scheduled action.','Surface suppression and duplicate membership before activation.','Show automation conditions and sequence stop rules as a readable flow.','Audit cross-lane contact overlap before introducing shared automation rules.'],preserve:'No campaign activation, contact enrollment or automation change is included.'},
 {name:'Lead Import',route:'leads',current:'CSV files go through mapping, cleaning and import jobs before records reach the CRM.',changes:['A direct route from the home screen and shared primary navigation.','Existing upload, mapping and job controls stay intact.'],proposals:['Show source, row totals, accepted, rejected and held rows before CRM write.','Surface unmapped roles/domains and missing project/contact lineage.','Offer downloadable row-level error reports and resumable partial failures.','Resolve the observed legacy lineage gaps before broadening automated intake.'],preserve:'CSV upload, mapping, active-job polling and recent imports.'},
 {name:'AI Content',route:'ai-content',current:'The content catalog includes creation, generated drafts, ideas and publishing workflows.',changes:['An explicit primary entry and home shortcut, with consistent shared chrome.','Small content/status labels are enlarged to 12px; controls have 44px height.','Mobile search and filters wrap within the screen.'],proposals:['Keep ideas, draft review, generated and published content easy to distinguish.','Show generation progress and actionable failure reasons alongside retry.','Expose state/topic coverage and potential overlap before creating more articles.','Keep publication and bulk actions deliberate and auditable.','Make WordPress sync status explicit; this page currently attempts a sync when opened. The local review blocks that write.'],preserve:'Existing creation, generation, review and publishing controls.'},
 {name:'Archive',route:'archive',current:'Archived document requests can be inspected and restored.',changes:['Archive remains one click inside More tools and is grouped with the rest of the workspace.'],proposals:['Add search, archive date/reason and a clear restoration result.','Show how a restored project re-enters the review queue.'],preserve:'The existing restore endpoint and action are unchanged.'},
 {name:'Roadmap',route:'roadmap',current:'Tasks track automation work, status and updates.',changes:['The same editable task board remains in the tools menu.'],proposals:['Group tasks by impact and owner; show dependencies and blockers.','Distinguish a shipped capability from an experiment or unconnected integration.','Link each completed task to acceptance evidence.'],preserve:'Task creation, editing, updates, status and deletion.'},
 {name:'Settings & documentation',route:'settings',current:'Settings, Methodology and System Docs explain document setup and system processes.',changes:['All three keep their existing pages in the grouped tools menu.'],proposals:['Separate editable settings from explanatory documentation.','Add integration health with last successful check and a clear next action.','Date technical documentation and link it to the deployed version.','Keep credentials server-side and label missing connections without asking staff to paste keys.'],preserve:'Existing configuration, methodology and system documentation.'},
];
export default function InterfaceReview({onNavigate}:{onNavigate:(view:WorkspaceView)=>void}){
 return <div className="workspace-review"><div className="workspace-page-heading"><div><p className="workspace-eyebrow">Local prototype · Review before release</p><h1>Interface review</h1><p>A restrained revamp of the shared workspace, with deeper improvements mapped by section.</p></div></div><div className="workspace-notice"><div><h2>Staff familiarity is the constraint</h2><p>This build changes shared navigation and adds Overview and Sales. Existing SDR screens and document/content/import workflows are retained. The recommendations below describe future work.</p></div></div><div className="workspace-review-summary"><span><Check size={18}/>Local prototype</span><span><Check size={18}/>Existing SDR retained</span><span><Check size={18}/>No Railway deployment</span></div>
  <div className="workspace-review-sections">{sections.map((section,index)=><details key={section.name} open={index<3}><summary><span><small>{String(index+1).padStart(2,'0')}</small>{section.name}</span><ChevronDown size={18}/></summary><div className="workspace-review-body"><p>{section.current}</p><div className="workspace-review-columns"><div><h3>In this local build</h3><ul>{section.changes.map(change=><li key={change}>{change}</li>)}</ul></div><div><h3>Internal improvements proposed</h3><ul>{section.proposals.map(proposal=><li key={proposal}>{proposal}</li>)}</ul></div></div><p className="workspace-preserved"><strong>Preserved:</strong> {section.preserve}</p><button className="workspace-text-link" onClick={()=>onNavigate(section.route)}>Open this work area<ArrowRight size={16}/></button></div></details>)}</div>
 </div>;
}
