// SDR email templates — extracted verbatim from the n8n SDR Automation workflow
// (workflow id pcUKAkMkvoKQ4kPY, "Build Future Email Activities" node).
//
// Phase 3 architecture shift: Apollo sequences own the cadence/timing.
// The Day-0 template here becomes the FIRST draft generated by our backend
// for human approval. Subsequent steps (day 3 / day 6) live INSIDE the Apollo
// sequence as configured by Derek in Apollo's UI — not generated by us.
//
// PB is single-touch (no follow-up); the other three triggers have follow-ups
// stored here only for reference and parity with the legacy n8n flow.
//
// Merge fields:
//   {First}  — contact's first name
//   {ENV}    — env program acronym (default "EPA")
//   {SWPPP}  — SWPPP program acronym (default "SWPPP")
//   {Sig}    — sender's signature (the renderer auto-appends "\nwww.ProSWPPP.com")

export const SDR_TEMPLATES = {
  AGC: [
    {
      day: 0,
      body: `{First},\n\nCongrats on winning the award on this one...\n\nJust wanted to ensure you're carrying our number on the {ENV} / {SWPPP} scope...\n\nWe just take care of all the {ENV} / {SWPPP} requirements... so you don't have to worry about it...\n\nYou should have a bid from us on it... let us know if you need a fresh copy.\n\nWe appreciate your business.\n\nRegards,\n{Sig}`,
    },
    {
      day: 3,
      body: `{First},\n\nY'all are going to carry our number on the {ENV} / {SWPPP} scope on this one, right?\n\nWe appreciate your business.\n\nRegards,\n{Sig}`,
    },
    {
      day: 6,
      body: `Hey {First},\n\nWe sent you a bid and called several times on the {ENV} / {SWPPP} scope on this one, but haven't heard anything...\n\nWhere do we go from here?\n\n{Sig}`,
    },
  ],

  LBA: [
    {
      day: 0,
      body: `{First},\n\nSaw y'all were low on this one, congrats...\n\nY'all are going to use our number on the {ENV} / {SWPPP} scope, right?\n\nWe appreciate your business.\n\nRegards,\n{Sig}`,
    },
    {
      day: 3,
      body: `{First},\n\nDo y'all have the {ENV} / {SWPPP} scope covered on this one?\n\nWe appreciate your business.\n\nRegards,\n{Sig}`,
    },
    {
      day: 6,
      body: `Hey {First},\n\nWe sent you a bid and called a few times on this one, but haven't heard anything...\n\nWhere do we go from here?\n\n{Sig}`,
    },
  ],

  CM: [
    {
      day: 0,
      body: `{First},\n\nSaw y'all are handling this one...\n\nIf you were to need the {ENV} / {SWPPP} scope covered just let us know how we can help... you should have a bid from us on same...\n\nWe appreciate your business.\n\nRegards,\n{Sig}`,
    },
    {
      day: 3,
      body: `{First},\n\nY'all have the {ENV} / {SWPPP} scope covered on this one?\n\nRegards,\n{Sig}`,
    },
    {
      day: 6,
      body: `Hey {First},\n\nWe sent you a bid and called a few times, but haven't heard anything...\n\nWhere do we go from here?\n\n{Sig}`,
    },
  ],

  PB: [
    {
      day: 0,
      body: `{First},\n\nDid y'all win this one? How do y'all cover the {ENV} / {SWPPP} scope?\n\nWe appreciate your business.\n\nRegards,\n{Sig}`,
    },
  ],
};

/**
 * Subject line convention — "<Project Name> <SWPPP-acronym>", matching the
 * actual emails Derek's team sends from Pipedrive (verified against the sent
 * mailbox, e.g. "Stadium Dr Imp SWPPP", "Tanner Williams Comm Pk Expansion
 * CBMPP"). The SWPPP acronym is the lead's resolved `{SWPPP}` merge value
 * (default "SWPPP"; some scopes/states use CBMPP etc.). Apollo sequence steps
 * can override per-step; this is just the default the draft starts with.
 */
export function defaultSubject(leadTitle, swpppAcronym) {
  const title = (leadTitle || "").trim();
  const acr = (swpppAcronym || "SWPPP").trim();
  return title ? `${title} ${acr}` : acr;
}

/**
 * Render a template body with the standard merge fields.
 * Signature auto-appends "\nwww.ProSWPPP.com" to match legacy behavior.
 */
export function renderTemplate(body, { first, env, swppp, sig } = {}) {
  return String(body)
    .replace(/\{First\}/g, first || "there")
    .replace(/\{ENV\}/g, env || "EPA")
    .replace(/\{SWPPP\}/g, swppp || "SWPPP")
    .replace(/\{Sig\}/g, (sig || "") + "\nwww.ProSWPPP.com");
}

/**
 * Produce the day-0 (first-touch) draft body for a trigger type.
 */
export function renderFirstTouch(triggerType, ctx) {
  const t = (triggerType || "").toUpperCase();
  const steps = SDR_TEMPLATES[t];
  if (!steps?.length) throw new Error(`Unknown trigger type: ${triggerType}`);
  return renderTemplate(steps[0].body, ctx);
}

/**
 * Return ALL steps rendered (mainly for previewing what an Apollo sequence
 * should be configured to send). Day-0 = first email, day-3/6 = follow-ups.
 */
export function renderAllSteps(triggerType, ctx) {
  const t = (triggerType || "").toUpperCase();
  const steps = SDR_TEMPLATES[t];
  if (!steps?.length) throw new Error(`Unknown trigger type: ${triggerType}`);
  return steps.map((s) => ({ day: s.day, body: renderTemplate(s.body, ctx) }));
}
