import { readFileSync } from 'node:fs';
import ts from 'typescript';
import { it, expect, vi } from 'vitest';
const source = readFileSync(new URL('../../src/components/SdrInterface.tsx', import.meta.url), 'utf8');
const transpile = (s) => ts.transpileModule(s, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }).outputText;
it('Priority rejects ineligible sends and future timestamps even with enough opens', () => {
    const block = source.slice(source.indexOf('const HIGH_INTENT_WINDOW_MS'), source.indexOf('// Priority "dismissed"'));
    const isHot = new Function(`${transpile(block)};return isHot;`)();
    const lead = { replies: 0, opens: 4, clicks: 0, send_status: 'sent', last_intent_at: new Date().toISOString(), priority_eligible: true };
    expect(isHot(lead)).toBe(true);
    expect(isHot({ ...lead, priority_eligible: false })).toBe(false);
    expect(isHot({ ...lead, last_intent_at: new Date(Date.now() + 100000).toISOString() })).toBe(false);
});
it('opens a second inboxLead hash without remount and ignores an older pending lookup', async () => {
    const start = source.indexOf('  useEffect(() => {', source.indexOf('// Deep-link from a forwarded reply'));
    const end = source.indexOf('  useEffect(() => {', start + 10);
    const target = new EventTarget();
    const window = { location: { hash: '#/sdr?inboxLead=one' }, history: { replaceState: vi.fn() }, addEventListener: target.addEventListener.bind(target), removeEventListener: target.removeEventListener.bind(target) };
    let resolveFirst = () => { };
    let opened = null;
    const sdrApi = { findLeadThread: async (id) => id === 'one' ? await new Promise(r => { resolveFirst = r; }) : { threadId: 'second', mailbox: 'rep@test' } };
    let cleanup = () => { };
    new Function('useEffect', 'window', 'sdrApi', 'goInbox', 'setDeepLeadId', transpile(source.slice(start, end)))((fn) => cleanup = fn(), window, sdrApi, (v) => { opened = v.threadId; }, () => { });
    window.location.hash = '#/sdr?inboxLead=two';
    target.dispatchEvent(new Event('hashchange'));
    await new Promise(r => setTimeout(r, 0));
    expect(opened).toBe('second');
    resolveFirst({ threadId: 'first', mailbox: 'rep@test' });
    await new Promise(r => setTimeout(r, 0));
    expect(opened).toBe('second');
    cleanup();
});
