import express from 'express';
import {readFileSync} from 'node:fs';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {reportingTestDb} from './reportingTestDb.js';
import {ownerScope,withLeadLock} from '../sdrAccess.js';
import {checkViewedDraft,checkDraftSchedule,draftContextHash,draftConflict,recordDraftApproval,checkApprovedDraft,serializeDraft,mutateViewedDraft} from '../sdrDraftRevision.js';
import {withProviderContactLock,reserveEnrollment,advanceEnrollmentPhase,recordPreAddRefusal,recordEnrollmentReceipt,recordEnrollmentUncertainty} from '../sdrProviderOperations.js';
const source=readFileSync(new URL('../../server.js',import.meta.url),'utf8');
const block=source.slice(source.indexOf('app.post("/api/sdr/drafts/:id/approve-and-send", async (req, res) => {'),source.indexOf('\napp.get("/api/projects", async (req, res) => {'));
const db=reportingTestDb('approval_repeat_recovery');
const draftId='10000000-0000-0000-0000-000000000001',actor='10000000-0000-0000-0000-000000000002',otherActor='10000000-0000-0000-0000-000000000003',mailboxId='10000000-0000-0000-0000-000000000004';
describe.skipIf(!db)('real approval gate and revision trigger across repeat requests',()=>{
 let server,base,currentActor,crmAllowed,sourceRevision,provider;
 const get=async()=>(await db.pool.query('SELECT * FROM sdr_drafts WHERE id=$1',[draftId])).rows[0];
 const request=async(view,as=actor)=>{currentActor=as;const response=await fetch(`${base}/api/sdr/drafts/${draftId}/approve-and-send`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({expectedRevision:String(view.revision),expectedContextHash:draftContextHash(view)})});return {status:response.status,body:await response.json()}};
 beforeAll(async()=>{
  await db.setup();await db.pool.query(`CREATE TABLE sdr_drafts(id uuid PRIMARY KEY,pipedrive_lead_id text,status text,sent_at timestamptz,subject text,body text,updated_at timestamptz DEFAULT NOW(),metadata jsonb,contact_id_snapshot text,contact_email_snapshot text,org_id_snapshot text,pipedrive_contact_id text,pipedrive_org_id text,assigned_mailbox_id uuid,assigned_user_id uuid,apollo_sequence_id text,trigger_type text,scheduled_for timestamptz,approved_at timestamptz,approved_by text,reject_reason text,error_message text,company_id text);
  CREATE TABLE sdr_sends(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),draft_id uuid,pipedrive_lead_id text,apollo_sequence_id text,apollo_contact_id text,mailbox_id uuid,status text,sent_at timestamptz,enrolled_trigger text,enrolled_person_id text,enrolled_org_id text,enrolled_stage text);
  CREATE TABLE permit_sends(id text,apollo_contact_id text);
  CREATE TABLE sdr_settings(id int,contact_cooldown_days int);INSERT INTO sdr_settings VALUES(1,14);
  CREATE TABLE sdr_message_facts(provider text,direction text,provider_status text,prospect_email text,occurred_at timestamptz);
  CREATE TABLE sdr_outreach_log(pipedrive_lead_id text,sent_at timestamptz,source text);
  CREATE TABLE sdr_lead_state(pipedrive_lead_id text,project_stage text);
  CREATE TABLE sdr_mailboxes(id uuid,email text,apollo_mailbox_id text,active boolean,warmup_started_at timestamptz,signature_html text,pipedrive_sender_id text,daily_send_limit int);`);
  for(const file of ['2026-10-07-sdr-draft-revisions.sql','2026-10-07-sdr-provider-operations.sql','2026-10-10-sdr-enrollment-phases.sql','2026-10-07-sdr-outreach-controls.sql'])await db.pool.query(await readFile(new URL('../../migrations/'+file,import.meta.url),'utf8'));
  provider={matchContactByEmail:vi.fn(async()=>({id:'contact'})),getContact:vi.fn(async()=>({id:'contact',contact_campaign_statuses:[]})),updateContactCustomFields:vi.fn(async()=>{}),addContactsToSequence:vi.fn(async()=>({contacts:[{id:'contact',contact_campaign_statuses:[{emailer_campaign_id:'sequence',emailer_campaign_contact_id:'membership',added_at:'2026-10-10T00:00:00Z'}]}]}))};
  const app=express();app.use(express.json());app.use((req,res,next)=>{req.sdrUser={sub:currentActor,role:currentActor===actor?'sdr':'admin',machine:false};next()});
  const deps={app,pool:db.pool,process:{env:{DATABASE_URL:'local-fixture',APOLLO_API_KEY:'local-fixture',PIPEDRIVE_API_TOKEN:'',SDR_CRM_COMPANY_ID:'42',SDR_REPLY_ACTIONS_ENABLED:''}},crypto:{randomUUID},console:{log:()=>{},warn:()=>{},error:()=>{}},ownerScope,withLeadLock,withProviderContactLock,checkViewedDraft,checkDraftSchedule,draftContextHash,draftConflict,recordDraftApproval,checkApprovedDraft,serializeDraft,mutateViewedDraft,
   staleDraftBlock:()=>null,isCustomerLead:async()=>null,contactCooldownDays:async()=>14,emailVerify:{verifyEnabled:()=>false},mailboxBounceHealth:async()=>new Map(),dailyCap:()=>10,mailboxSentToday:async()=>0,rampDay:()=>1,bounceStepPenalty:()=>0,
   assertSendSafety:async(_pool,draft)=>({companyId:'42',leadId:'lead',personId:'person',recipientEmail:'buyer@example.test',organizationId:'org',projectRole:null,stage:'Bid',trigger:'LBA',mailboxId:String(draft.assigned_mailbox_id),sequenceId:'sequence',scheduledFor:null,overrideDecisionId:null,roleExceptionId:null,cadence:'standard',sourceRevision,draftId:String(draft.id),channel:'email',serviceId:null,technicalComplete:true}),
   readContactSendDaysAgo:async()=>null,reserveEnrollment,advanceEnrollmentPhase,recordPreAddRefusal,recordEnrollmentReceipt,recordEnrollmentUncertainty,enrollmentRetryEnabled:()=>false,enrollmentSendBlock:()=>null,crmLifecycleEnabled:()=>true,verifyCrmLead:async()=>({allowed:crmAllowed,reason:'crm_missing',retryable:false}),
   APOLLO_CF_DRAFT_SUBJECT:'subject',APOLLO_CF_DRAFT_BODY:'body',APOLLO_CF_TRACK:'track',APOLLO_CF_ENV:null,APOLLO_CF_SWPPP:null,pdSequenceStartedKey:'sequence_started',apolloClient:provider,pipedriveClient:{},publishOutreachEvent:async()=>{}};
  new Function(...Object.keys(deps),block)(...Object.values(deps));server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}`;
 });
 afterAll(async()=>{await new Promise(r=>server.close(r));await db.close()});
 beforeEach(async()=>{crmAllowed=false;sourceRevision='source-1';currentActor=actor;vi.clearAllMocks();await db.pool.query('TRUNCATE sdr_draft_approvals,sdr_provider_membership_observations,sdr_provider_operations,sdr_outreach_control_decisions,sdr_outreach_controls,sdr_sends,sdr_drafts,sdr_outreach_log,sdr_lead_state,sdr_mailboxes');await db.pool.query(`INSERT INTO sdr_drafts(id,pipedrive_lead_id,status,subject,body,metadata,contact_id_snapshot,contact_email_snapshot,org_id_snapshot,pipedrive_contact_id,pipedrive_org_id,assigned_mailbox_id,assigned_user_id,apollo_sequence_id,trigger_type,company_id) VALUES($1,'lead','pending','Subject','Body','{}','person','buyer@example.test','org','person','org',$2,$3,'sequence','LBA','42')`,[draftId,mailboxId,actor]);await db.pool.query("INSERT INTO sdr_lead_state VALUES('lead','Bid')");await db.pool.query('INSERT INTO sdr_mailboxes VALUES($1,\'sender@example.test\',\'provider-mailbox\',true,NULL,NULL,NULL,10)',[mailboxId]);});
 it('keeps the exact approved revision on deliberate repeat and reaches a new reservation/add',async()=>{const first=await get();expect((await request(first)).status).toBe(409);const afterRefusal=await get();expect(afterRefusal).toMatchObject({status:'approved',revision:'2'});expect((await db.pool.query('SELECT state,draft_revision FROM sdr_provider_operations')).rows).toEqual([{state:'pre_add_refused',draft_revision:'2'}]);crmAllowed=true;const second=await request(afterRefusal);expect(second.status).toBe(200);expect(provider.addContactsToSequence).toHaveBeenCalledTimes(1);expect((await db.pool.query('SELECT state,draft_revision FROM sdr_provider_operations ORDER BY created_at,id')).rows).toEqual([{state:'pre_add_refused',draft_revision:'2'},{state:'confirmed',draft_revision:'2'}]);expect((await db.pool.query('SELECT revision FROM sdr_drafts')).rows[0].revision).toBe('3');expect((await db.pool.query('SELECT count(*)::int n FROM sdr_draft_approvals')).rows[0].n).toBe(2);});
 it('rejects a stale view before the second provider call',async()=>{const first=await get();await request(first);crmAllowed=true;expect((await request(first)).body.code).toBe('draft_stale');expect(provider.addContactsToSequence).not.toHaveBeenCalled();});
 it('keeps a different actor blocked by exact revision',async()=>{await request(await get());crmAllowed=true;expect((await request(await get(),otherActor)).body.code).toBe('provider_operation_requires_review');expect(provider.addContactsToSequence).not.toHaveBeenCalled();});
 it('keeps a fresh source-context change blocked',async()=>{await request(await get());sourceRevision='source-2';crmAllowed=true;expect((await request(await get())).body.code).toBe('provider_operation_requires_review');expect(provider.addContactsToSequence).not.toHaveBeenCalled();});
 it('keeps an additional uncertain operation blocking the exact terminal row',async()=>{await request(await get());await db.pool.query(`INSERT INTO sdr_provider_operations(id,operation_key,kind,contact_id,campaign_id,lead_id,expected_membership,action_id,state) VALUES(gen_random_uuid(),'other-operation','enroll','contact','sequence','lead','{}','other','unresolved')`);crmAllowed=true;expect((await request(await get())).body.code).toBe('provider_operation_requires_review');expect(provider.addContactsToSequence).not.toHaveBeenCalled();});
 it('keeps changed copy blocked at a new revision',async()=>{await request(await get());const reviewed=await get();await mutateViewedDraft(db.pool,{draft:reviewed,expectedRevision:reviewed.revision,expectedContextHash:draftContextHash(reviewed),fields:{body:'Changed copy',status:'edited'}});crmAllowed=true;expect((await request(await get())).body.code).toBe('provider_operation_requires_review');expect(provider.addContactsToSequence).not.toHaveBeenCalled();});
 it('requires a valid latest same-actor receipt before preserving an approved version',async()=>{await request(await get());await db.pool.query(`INSERT INTO sdr_draft_approvals(draft_id,revision,context_hash,subject,body,context,actor,created_at) SELECT draft_id,revision,context_hash,subject,body,context,$1,NOW()+INTERVAL '1 second' FROM sdr_draft_approvals ORDER BY created_at DESC LIMIT 1`,[{accountId:otherActor,execution:'interactive',source:'sdr_ui'}]);crmAllowed=true;expect((await request(await get())).body.code).toBe('provider_operation_requires_review');expect((await get()).revision).toBe('3');expect(provider.addContactsToSequence).not.toHaveBeenCalled();});
});
