import {readFileSync} from 'node:fs';
import {describe,it,expect,vi} from 'vitest';
const source=readFileSync(new URL('../../server.js',import.meta.url),'utf8');
const segment=source.slice(source.indexOf('        const reservation=await reserveEnrollment('),source.indexOf('        enrollResponse = await enrollContact();')+'        enrollResponse = await enrollContact();'.length);
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const runSegment=new AsyncFunction('d',`const {client,draft,current,safetyContext,apolloContactId,apolloClient,mailbox,crypto,reserveEnrollment,advanceEnrollmentPhase,recordPreAddRefusal,assertCurrentEnrollment,assertSendSafety,crmLifecycleEnabled,verifyCrmLead,APOLLO_CF_DRAFT_SUBJECT,APOLLO_CF_DRAFT_BODY,APOLLO_CF_TRACK,APOLLO_CF_ENV,APOLLO_CF_SWPPP,pool,process}=d;let enrollResponse;${segment};return enrollResponse;`);
const setup=()=>{
 const events=[];const refusal=vi.fn(async()=>events.push('refusal'));
 const deps={client:{},pool:{},draft:{id:'draft',subject:'subject',body:'body',metadata:{},pipedrive_lead_id:'lead',apollo_sequence_id:'sequence'},current:{revision:1},safetyContext:{companyId:'42',draftId:'draft',leadId:'lead'},apolloContactId:'contact',mailbox:{apollo_mailbox_id:'mailbox'},crypto:{randomUUID:()=> 'action'},reserveEnrollment:vi.fn(async args=>{events.push('reserve');expect(args.enrollmentMode).toBe('sdr_draft_v1');return {reservationId:'reservation'}}),advanceEnrollmentPhase:vi.fn(async ({nextPhase})=>events.push(nextPhase)),recordPreAddRefusal:refusal,assertCurrentEnrollment:vi.fn(async()=>events.push('guard')),assertSendSafety:vi.fn(async()=>events.push('safety')),crmLifecycleEnabled:()=>true,verifyCrmLead:vi.fn(async()=>({allowed:true})),APOLLO_CF_DRAFT_SUBJECT:'subject',APOLLO_CF_DRAFT_BODY:'body',APOLLO_CF_TRACK:'track',APOLLO_CF_ENV:null,APOLLO_CF_SWPPP:null,process:{env:{SDR_CRM_COMPANY_ID:'42'}},apolloClient:{updateContactCustomFields:vi.fn(async()=>events.push('fields_call')),addContactsToSequence:vi.fn(async()=>{events.push('add_call');return {contacts:[]}})}};
 return {deps,events,refusal};
};
describe('real approval route provider boundary',()=>{
 it('marks each network boundary before its call',async()=>{const {deps,events}=setup();await runSegment(deps);expect(events).toEqual(['reserve','guard','safety','fields_started','fields_call','fields_completed','guard','guard','safety','add_started','add_call']);});
 it('records only an explicit returned CRM denial after fields complete',async()=>{const {deps,events,refusal}=setup();deps.verifyCrmLead.mockResolvedValue({allowed:false,reason:'crm_missing',retryable:false});await expect(runSegment(deps)).rejects.toMatchObject({code:'crm_missing'});expect(refusal).toHaveBeenCalledWith(expect.objectContaining({refusal:{kind:'crm_returned_denial',reason:'crm_missing'}}));expect(events).toContain('fields_completed');expect(deps.apolloClient.addContactsToSequence).not.toHaveBeenCalled();});
 it('leaves field uncertainty and generic CRM exceptions blocking',async()=>{for(const point of ['fields','crm']){const {deps,refusal}=setup();if(point==='fields')deps.apolloClient.updateContactCustomFields.mockRejectedValue(Error('timeout'));else deps.verifyCrmLead.mockRejectedValue(Error('transport'));await expect(runSegment(deps)).rejects.toThrow();expect(refusal).not.toHaveBeenCalled();expect(deps.apolloClient.addContactsToSequence).not.toHaveBeenCalled();}});
 it('prevents add after failed durable add marker',async()=>{const {deps,refusal}=setup();deps.advanceEnrollmentPhase.mockImplementation(async ({nextPhase})=>{if(nextPhase==='add_started')throw Error('db unavailable')});await expect(runSegment(deps)).rejects.toThrow('db unavailable');expect(refusal).not.toHaveBeenCalled();expect(deps.apolloClient.addContactsToSequence).not.toHaveBeenCalled();});
 it('prevents add when the completed-fields marker cannot persist',async()=>{const {deps,refusal}=setup();deps.advanceEnrollmentPhase.mockImplementation(async ({nextPhase})=>{if(nextPhase==='fields_completed')throw Error('marker unavailable')});await expect(runSegment(deps)).rejects.toThrow('marker unavailable');expect(refusal).not.toHaveBeenCalled();expect(deps.apolloClient.addContactsToSequence).not.toHaveBeenCalled();});
 it('does not enter add after a terminal-refusal write fails',async()=>{const {deps,refusal}=setup();deps.verifyCrmLead.mockResolvedValue({allowed:false,reason:'crm_missing',retryable:false});refusal.mockRejectedValue(Error('receipt unavailable'));await expect(runSegment(deps)).rejects.toThrow('receipt unavailable');expect(deps.apolloClient.addContactsToSequence).not.toHaveBeenCalled();});
});
const wrapper=source.slice(source.indexOf('      const r = await runAutoOutreach(pool, { mailboxSentToday });'),source.indexOf('    })\n      .catch((e) => console.error("[auto-outreach] run failed:"'));
const runWrapper=new AsyncFunction('outcome',`const pool={},mailboxSentToday=async()=>0,runAutoOutreach=async()=>outcome,enrollAutoDrafts=async()=>({enrolled:0,skipped:0}),recovered={enrolled:0,skipped:0};${wrapper}`);
it('reports scan ceiling as partial coverage with selected, scanned and refused counts',async()=>{expect(await runWrapper({mode:'queue',created:0,capacity:1,eligible:50,scanned:50,refused:50,scanLimitReached:true,errors:[]})).toMatchObject({coverage:'partial',counts:{capacity:1,selected:50,scanned:50,refused:50,scanLimitReached:1}})});
