import {beforeAll,beforeEach,afterAll,describe,it,expect,vi} from 'vitest';
import fs from 'node:fs/promises';
import {reportingTestDb} from './reportingTestDb.js';
import {readFollowupDraft,saveFollowupDraft} from '../sdrFollowupDrafts.js';
import {createFollowupHandoffs} from '../sdrFollowupHandoffs.js';
const db=reportingTestDb('followup_handoffs');
const viewer={role:'sdr',sub:'00000000-0000-0000-0000-00000000000a'},companyId='42',leadId='A';
let service,client,evidence,input;
(db?describe:describe.skip)('explicit prepared response publication',()=>{
 beforeAll(async()=>{await db.setup();for(const file of ['2026-10-05-sdr-crm-observations.sql','2026-10-07-sdr-outreach-controls.sql'])await db.pool.query(await fs.readFile(new URL('../../migrations/'+file,import.meta.url),'utf8'));
 await db.pool.query('CREATE TABLE sdr_users(id uuid PRIMARY KEY,role text,active boolean); CREATE TABLE sdr_lead_state(pipedrive_lead_id text PRIMARY KEY,crm_company_id text); CREATE TABLE sdr_drafts(pipedrive_lead_id text,assigned_user_id uuid,status text)');
 for(const file of ['2026-10-08-sdr-followup-drafts.sql','2026-10-10-sdr-followup-handoffs.sql','2026-10-10-sdr-followup-handoffs.sql'])await db.pool.query(await fs.readFile(new URL('../../migrations/'+file,import.meta.url),'utf8'));});
 afterAll(async()=>db.close());
 beforeEach(async()=>{await db.pool.query('TRUNCATE sdr_followup_handoffs,sdr_followup_drafts,sdr_users,sdr_crm_snapshots,sdr_lead_state,sdr_drafts,sdr_outreach_controls,sdr_crm_links,sdr_crm_scope_coverage CASCADE');
 await db.pool.query('INSERT INTO sdr_users VALUES($1,$2,true)',[viewer.sub,viewer.role]);await db.pool.query(`INSERT INTO sdr_lead_state VALUES('A','42'); INSERT INTO sdr_crm_snapshots(company_id,entity,entity_id,data) VALUES('42','lead','A','{"title":"Project A","person_id":12,"owner_id":7}')`);
 const initial=await readFollowupDraft(db.pool,{viewer,companyId,leadId});const saved=await saveFollowupDraft(db.pool,{viewer,companyId,leadId,subject:'Project <A>',body:'<script>bad</script>\n'+ 'Full text '.repeat(300),expectedRevision:0,contextToken:initial.contextToken});input={viewer,leadId,expectedRevision:1,contextToken:saved.contextToken};
 evidence={complete:true,lead:{id:'A',title:'Project A',owner_id:7,person_id:12,is_archived:false},person:{id:12,name:'Buyer',email:[{value:'buyer@example.test',primary:true}]},organization:null,notes:[],activities:[{id:5,lead_id:'A',subject:'Call',done:false,due_date:'2026-10-14',user_id:7}]};
 client={validateIdentity:vi.fn(async()=>{}),readEvidence:vi.fn(async()=>structuredClone(evidence)),addNote:vi.fn(async()=>({id:91})),getNote:vi.fn(async()=>({id:91,lead_id:'A',content:client.addNote.mock.calls[0][0].content})),listNotes:vi.fn(async()=>({complete:true,items:[]}))};
 service=createFollowupHandoffs({pool:db.pool,companyId,sourceHost:'proswpppllc.pipedrive.com',client});});
 it('publishes full escaped message once after human confirmation and independent readback',async()=>{const preview=await service.preview(input);expect(preview.replyCoverage).toBe('unverified');expect(preview.content.body.length).toBeGreaterThan(1500);expect(preview.noteHtml).toContain('&lt;script&gt;');expect(preview.noteHtml).not.toContain('<script>');
 const request={...input,previewToken:preview.previewToken,latestConversationReviewed:true};const one=await service.publish(request),two=await service.publish(request);expect(one).toMatchObject({status:'confirmed',readbackVerified:true,noteId:'91'});expect(two.id).toBe(one.id);expect(client.addNote).toHaveBeenCalledTimes(1);expect(client.addNote.mock.calls[0][0].content).toContain('Full text '.repeat(300));});
 it('requires explicit review and rejects live task changes',async()=>{const p=await service.preview(input);await expect(service.publish({...input,previewToken:p.previewToken})).rejects.toMatchObject({code:'conversation_review_required'});evidence.activities[0].due_date='2026-10-20';await expect(service.publish({...input,previewToken:p.previewToken,latestConversationReviewed:true})).rejects.toMatchObject({code:'context_changed'});expect(client.addNote).not.toHaveBeenCalled();});
 it('never retries an uncertain POST, including after a new draft revision',async()=>{client.addNote.mockRejectedValue(new Error('timeout'));const p=await service.preview(input);const receipt=await service.publish({...input,previewToken:p.previewToken,latestConversationReviewed:true});expect(receipt.status).toBe('uncertain');expect((await service.preview(input)).publication.id).toBe(receipt.id);
 const saved=await saveFollowupDraft(db.pool,{viewer,companyId,leadId,subject:'Changed',body:'New revision',expectedRevision:1,contextToken:input.contextToken});expect((await service.preview({...input,expectedRevision:saved.draft.revision})).publication).toMatchObject({id:receipt.id,revision:1,status:'uncertain'});expect(client.addNote).toHaveBeenCalledTimes(1);});
 it('reconciles only an exact note on the correct lead and never writes again',async()=>{client.addNote.mockRejectedValue(new Error('timeout'));const p=await service.preview(input);const r=await service.publish({...input,previewToken:p.previewToken,latestConversationReviewed:true});client.listNotes.mockResolvedValue({complete:true,items:[{id:91,lead_id:'B',content:p.noteHtml}]});expect((await service.reconcile({viewer,leadId,handoffId:r.id})).status).toBe('uncertain');client.listNotes.mockResolvedValue({complete:true,items:[{id:91,lead_id:'A',content:p.noteHtml}]});expect((await service.reconcile({viewer,leadId,handoffId:r.id})).status).toBe('confirmed');expect(client.addNote).toHaveBeenCalledTimes(1);});
 it('rejects machine, other author and revoked sessions before any provider call',async()=>{await expect(service.preview({...input,viewer:{...viewer,machine:true}})).rejects.toMatchObject({code:'session_required'});await db.pool.query('UPDATE sdr_users SET active=false');await expect(service.preview(input)).rejects.toMatchObject({code:'session_required'});expect(client.validateIdentity).not.toHaveBeenCalled();});
 it('collected prepared note does not replace private draft context or cause fresh review',async()=>{const before=await readFollowupDraft(db.pool,{companyId,leadId,viewer});
 await db.pool.query(`INSERT INTO sdr_crm_snapshots(company_id,entity,entity_id,data) VALUES('42','note','prepared',$1)`,[{content:'[Auto] [Prepared response — unsent]<br>[SDR prepared handoff 00000000-0000-0000-0000-000000000001]<br>Draft only'}]);await db.pool.query(`INSERT INTO sdr_crm_links VALUES('42','note','prepared','lead','A','fixture')`);
 const after=await readFollowupDraft(db.pool,{companyId,leadId,viewer});expect(after.contextToken).toBe(before.contextToken);expect(after.context.records).toHaveLength(0);
 });
 it('supports v2 person emails but rejects an archived live lead or missing source completeness',async()=>{evidence.person.emails=evidence.person.email;delete evidence.person.email;expect((await service.preview(input)).contact.email).toBe('buyer@example.test');evidence.lead.is_archived=true;await expect(service.preview(input)).rejects.toMatchObject({code:'source_unavailable'});evidence.lead.is_archived=false;evidence.complete=false;await expect(service.preview(input)).rejects.toMatchObject({code:'source_unavailable'});expect(client.addNote).not.toHaveBeenCalled();
 });
 it('serializes shared-lead authors and blocks uncertainty across authors',async()=>{const other={...viewer,sub:'00000000-0000-0000-0000-00000000000b'};await db.pool.query('INSERT INTO sdr_users VALUES($1,$2,true)',[other.sub,other.role]);const current=await readFollowupDraft(db.pool,{companyId,leadId,viewer:other});await saveFollowupDraft(db.pool,{companyId,leadId,viewer:other,subject:'Other',body:'Other human draft',expectedRevision:0,contextToken:current.contextToken});const otherInput={...input,viewer:other,contextToken:current.contextToken};const a=await service.preview(input),b=await service.preview(otherInput);client.addNote.mockRejectedValue(new Error('timeout'));await service.publish({...input,previewToken:a.previewToken,latestConversationReviewed:true});await expect(service.publish({...otherInput,previewToken:b.previewToken,latestConversationReviewed:true})).rejects.toMatchObject({code:'publication_unresolved'});expect(client.addNote).toHaveBeenCalledTimes(1);});
 it('accepts only equivalent br normalization, refusing changed text and deleted notes',async()=>{const p=await service.preview(input);client.getNote.mockImplementation(async()=>({id:91,lead_id:'A',content:p.noteHtml.replaceAll('<br>','<br />')}));expect((await service.publish({...input,previewToken:p.previewToken,latestConversationReviewed:true})).status).toBe('confirmed');
 });
 it('rejects v2 soft deleted people and leads',async()=>{evidence.person.is_deleted=true;await expect(service.preview(input)).rejects.toMatchObject({code:'source_unavailable'});delete evidence.person.is_deleted;evidence.lead.is_deleted=true;await expect(service.preview(input)).rejects.toMatchObject({code:'source_unavailable'});expect(client.addNote).not.toHaveBeenCalled();});
 it('reconciliation refuses soft deleted notes and altered text, then releases the lead hold after verified readback',async()=>{client.addNote.mockRejectedValue(new Error('timeout'));const p=await service.preview(input);const r=await service.publish({...input,previewToken:p.previewToken,latestConversationReviewed:true});
 for(const changed of [{is_deleted:true},{deleted:true},{active_flag:false},{content:p.noteHtml+'altered'}]){client.listNotes.mockResolvedValue({complete:true,items:[{id:91,lead_id:'A',content:p.noteHtml,...changed}]});expect((await service.reconcile({viewer,leadId,handoffId:r.id})).status).toBe('uncertain');}
 client.listNotes.mockResolvedValue({complete:true,items:[{id:91,lead_id:'A',content:p.noteHtml.replaceAll('<br>','<br />')}]});expect((await service.reconcile({viewer,leadId,handoffId:r.id})).status).toBe('confirmed');
 const saved=await saveFollowupDraft(db.pool,{viewer,companyId,leadId,subject:'New subject',body:'Revised human text',expectedRevision:1,contextToken:input.contextToken});expect((await service.preview({...input,expectedRevision:saved.draft.revision})).previewToken).toBeTypeOf('string');expect(client.addNote).toHaveBeenCalledTimes(1);
 });
 it('records known expiry before POST as not attempted and permits a new revision',async()=>{let calls=0;const clock=()=>new Date(calls++<5?'2026-10-10T00:00:00Z':'2026-10-10T00:10:00Z');service=createFollowupHandoffs({pool:db.pool,companyId,sourceHost:'proswpppllc.pipedrive.com',client,now:clock});const p=await service.preview(input);const r=await service.publish({...input,previewToken:p.previewToken,latestConversationReviewed:true});expect(r).toMatchObject({status:'not_attempted',reason:'preview_expired'});expect(client.addNote).not.toHaveBeenCalled();expect((await service.reconcile({viewer,leadId,handoffId:r.id})).status).toBe('not_attempted');
 const saved=await saveFollowupDraft(db.pool,{viewer,companyId,leadId,subject:'New subject',body:'Revised human text',expectedRevision:1,contextToken:input.contextToken});expect((await service.preview({...input,expectedRevision:saved.draft.revision})).previewToken).toBeTypeOf('string');
 });
 it('keeps the durable reservation after a successful POST followed by receipt storage failure',async()=>{
 const p=await service.preview(input),args={...input,previewToken:p.previewToken,latestConversationReviewed:true};
 const original=db.pool.query.bind(db.pool);let failed=false;
 const spy=vi.spyOn(db.pool,'query').mockImplementation((sql,...values)=>{if(!failed&&String(sql).startsWith('UPDATE sdr_followup_handoffs SET status=')){failed=true;return Promise.reject(new Error('receipt storage failed'));}return original(sql,...values);});
 try{await expect(service.publish(args)).rejects.toThrow('receipt storage failed');}finally{spy.mockRestore();}
 const receipt=await service.publish(args);expect(receipt.status).toBe('reserved');expect(client.addNote).toHaveBeenCalledTimes(1);
 client.listNotes.mockResolvedValue({complete:true,items:[{id:91,lead_id:'A',content:p.noteHtml}]});expect((await service.reconcile({viewer,leadId,handoffId:receipt.id})).status).toBe('confirmed');expect(client.addNote).toHaveBeenCalledTimes(1);
 });
 it('leaves uncertain receipts unresolved for incomplete pagination and duplicate matching notes',async()=>{
 client.addNote.mockRejectedValue(new Error('timeout'));const p=await service.preview(input);const r=await service.publish({...input,previewToken:p.previewToken,latestConversationReviewed:true});
 const note={id:91,lead_id:'A',content:p.noteHtml};
 for(const page of [{complete:false,items:[note]},{complete:true,items:[note,{...note,id:92}]}]){client.listNotes.mockResolvedValue(page);expect((await service.reconcile({viewer,leadId,handoffId:r.id})).status).toBe('uncertain');}expect(client.addNote).toHaveBeenCalledTimes(1);
 });
 it('concurrent publication reserves once',async()=>{const p=await service.preview(input);const args={...input,previewToken:p.previewToken,latestConversationReviewed:true};await Promise.all([service.publish(args),service.publish(args)]);expect(client.addNote).toHaveBeenCalledTimes(1);});
});
