import {it,expect,vi} from 'vitest';
import {createFollowupHandoffClient} from '../sdrFollowupHandoffClient.js';
const config={token:'synthetic-not-secret',companyId:'42',sourceHost:'proswpppllc.pipedrive.com'};
const response=data=>({ok:true,json:async()=>({success:true,data})});
it('validates both live company ID and domain, failing closed',async()=>{for(const me of [{company_id:43,company_domain:'proswpppllc'},{company_id:42,company_domain:'other'},{company_id:42}]){const fetchImpl=vi.fn(async()=>response(me));await expect(createFollowupHandoffClient({...config,fetchImpl}).validateIdentity()).rejects.toThrow();expect(fetchImpl).toHaveBeenCalledTimes(1);}
 const fetchImpl=vi.fn(async()=>response({company_id:42,company_domain:'proswpppllc'}));await createFollowupHandoffClient({...config,fetchImpl}).validateIdentity();expect(String(fetchImpl.mock.calls[0][0])).toContain('/v1/users/me');expect(fetchImpl.mock.calls[0][1].method).toBe('GET');});
it('appends exactly one lead note with a bounded request, no retry on timeout',async()=>{const fetchImpl=vi.fn(async()=>{throw new Error('timeout');});const client=createFollowupHandoffClient({...config,fetchImpl});await expect(client.addNote({leadId:'A',content:'Human text'})).rejects.toThrow('timeout');expect(fetchImpl).toHaveBeenCalledTimes(1);const [url,options]=fetchImpl.mock.calls[0];expect(new URL(url).pathname).toBe('/v1/notes');expect(options.method).toBe('POST');expect(JSON.parse(options.body)).toEqual({lead_id:'A',content:'Human text'});expect(options.signal).toBeInstanceOf(AbortSignal);expect(Object.keys(client).sort()).toEqual(['addNote','getNote','listNotes','readEvidence','validateIdentity']);});
it('rejects alternate or credential-bearing source hosts before requests',()=>{for(const sourceHost of ['other.pipedrive.com','https://proswpppllc.pipedrive.com','user@proswpppllc.pipedrive.com'])expect(()=>createFollowupHandoffClient({...config,sourceHost})).toThrow();});
it('readback only performs a GET on the exact encoded note ID',async()=>{const fetchImpl=vi.fn(async()=>response({id:91,lead_id:'A',content:'x'}));await createFollowupHandoffClient({...config,fetchImpl}).getNote('91');expect(fetchImpl.mock.calls[0][1].method).toBe('GET');expect(new URL(fetchImpl.mock.calls[0][0]).pathname).toBe('/v1/notes/91');});
it('retains raw archive status rather than trusting the observer active-endpoint assumption',async()=>{const fetchImpl=vi.fn(async url=>{const path=new URL(url).pathname;if(path==='/v1/leads/A')return response({id:'A',owner_id:7,is_archived:true});if(path==='/v1/notes')return {ok:true,json:async()=>({success:true,data:[],additional_data:{pagination:{more_items_in_collection:false}}})};if(path==='/api/v2/activities')return {ok:true,json:async()=>({success:true,data:[],additional_data:{next_cursor:null}})};throw Error('Unexpected endpoint');});const result=await createFollowupHandoffClient({...config,fetchImpl}).readEvidence('A');expect(result.complete).toBe(true);expect(result.lead.is_archived).toBe(true);expect(fetchImpl.mock.calls.every(([,opts])=>opts.method==='GET')).toBe(true);});
