import {describe,it,expect,vi} from 'vitest';
let register;try{register=(await import('../sdrPreparationEvidenceRoutes.js')).registerSdrPreparationEvidenceRoutes;}catch{}
const viewer={role:'admin',sub:'00000000-0000-0000-0000-000000000001'};
function setup(){expect(register).toBeTypeOf('function');const routes=new Map(),readOrders=vi.fn(async()=>({items:[],total:0})),readDelivery=vi.fn(async()=>({items:[],total:0}));register({get:(p,h)=>routes.set(p,h)},{pool:{},companyId:'13105180',readOrders,readDelivery});return {routes,readOrders,readDelivery};}
const response=()=>({code:200,headers:{},set(k,v){this.headers[k]=v;return this;},status(code){this.code=code;return this;},json(value){this.value=value;return this;}});
describe('read-only preparation evidence routes',()=>{
 it('registers GETs and forwards validated parameters with no-store',async()=>{const {routes,readOrders}=setup();const res=response();await routes.get('/api/sdr/crm/leads/:leadId/order-candidates')({sdrUser:viewer,params:{leadId:'A'},query:{q:'literal%',offset:'20'},originalUrl:'/api/sdr/crm/leads/A/order-candidates?q=literal%25&offset=20'},res);expect(res.code).toBe(200);expect(res.headers['Cache-Control']).toBe('no-store');expect(readOrders).toHaveBeenCalledWith({},expect.objectContaining({companyId:'13105180',viewer,leadId:'A',query:'literal%',offset:20}));});
 it.each([{query:{offset:'-1'}},{query:{offset:'10001'}},{query:{q:['a','b']}},{query:{companyId:'other'}},{query:{q:'a'},originalUrl:'/?q=a&q=b'},{query:{},originalUrl:'/?offset=0&offset=0'}])('rejects query pollution %j',async input=>{const {routes,readOrders}=setup(),res=response();await routes.get('/api/sdr/crm/leads/:leadId/order-candidates')({sdrUser:viewer,params:{leadId:'A'},...input},res);expect(res.code).toBe(400);expect(readOrders).not.toHaveBeenCalled();});
 it('rejects anonymous/machine/staff sessions and masks private failures',async()=>{const {routes,readDelivery}=setup(),handler=routes.get('/api/sdr/health/delivery-evidence');for(const user of [null,{...viewer,machine:true},{...viewer,role:'sdr'}]){const res=response();await handler({sdrUser:user,query:{}},res);expect([401,403]).toContain(res.code);}readDelivery.mockRejectedValueOnce(Error('secret'));const res=response();await handler({sdrUser:viewer,query:{}},res);expect(res.code).toBe(503);expect(JSON.stringify(res.value)).not.toContain('secret');});
 it('maps current-role revocation to 403 and unavailable lead to 404',async()=>{const {routes,readOrders}=setup();for(const [code,want] of [['admin_required',403],['lead_unavailable',404]]){readOrders.mockRejectedValueOnce(Object.assign(Error(code),{code}));const res=response();await routes.get('/api/sdr/crm/leads/:leadId/order-candidates')({sdrUser:viewer,params:{leadId:'A'},query:{}},res);expect(res.code).toBe(want);}});
 it('refuses filters and duplicate parameters on delivery',async()=>{const {routes,readDelivery}=setup(),res=response();await routes.get('/api/sdr/health/delivery-evidence')({sdrUser:viewer,query:{},originalUrl:'/?mailbox=a&mailbox=b'},res);expect(res.code).toBe(400);expect(readDelivery).not.toHaveBeenCalled();});
});
