import {getDeliveryEvidence,type DeliveryEvidenceData} from '../../../lib/sdrPreparationEvidenceApi';
import {useEvidenceRead} from '../useEvidenceRead';
const stamp=(value:string)=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('en-US',{timeZone:'America/Chicago'})+' CT':'Unknown';
const reason=(value:string)=>value==='unclassified'?'Reason unavailable':value.replaceAll('_',' ');
export function DeliveryEvidenceView({data}:{data:DeliveryEvidenceData}){return <div>
 <p>{data.total} scoped enrollment records · Showing {data.items.length}, newest local enrollment first. Local enrollment times do not prove a send.</p>
 {data.items.map(item=><details key={item.sendId}><summary>{item.projectTitle||item.leadId} · {item.receipt?'Exact completed message receipt':'No exact message receipt recorded'}</summary><p>Local enrollment: {stamp(item.localEnrollmentAt)} · Stored status: {item.storedStatus}</p><p>{item.mailbox} → Historical draft recipient: {item.historicalRecipient||'Unknown'}</p>{item.receipt?<p>Provider completion time: {stamp(item.receipt.occurredAt)} · Observed {stamp(item.receipt.observedAt)} · Message {item.receipt.providerMessageId}</p>:<p>No exact message receipt recorded. Delivery remains unknown.</p>}<p>Enrollment {item.sendId} · Project {item.leadId}</p><p>{item.operationTotal} scoped provider operation records{item.operationTotal>item.operations.length?` · Showing ${item.operations.length}`:''}. Stored operation state is not proof of current provider membership.</p>{item.operations.map(operation=><p key={operation.id}>{operation.kind} · {reason(operation.state)} · {operation.reason?reason(operation.reason):'No reason recorded'} · Updated {stamp(operation.updatedAt)}</p>)}</details>)}
 <details><summary>Recorded safety checks · {data.safetyChecks.total} held or requiring review</summary><p>Showing {data.safetyChecks.items.length} unique decision receipts for current draft revisions. First recorded times are not retry attempt times; repeated identical checks may share one receipt.</p>{data.safetyChecks.items.map(check=><div key={check.decisionId}><strong>{check.projectTitle||check.leadId} · {check.outcome==='hold'?'Recorded safety check held':'Recorded safety check requires review'}</strong><p>{check.mailbox} · Draft revision {check.draftRevision} · First recorded {stamp(check.firstRecordedAt)}</p><p>{check.reasons.map(reason).join(' · ')||'Reason unavailable'}</p></div>)}</details>
 <p className="sdr-reply-backlog-meta">Coverage is partial: {data.coverage.visibleMailboxes} connected inboxes; collected Apollo receipts only, unique direct message IDs with matching campaign, historical recipient and sending mailbox. Missing or conflicting evidence remains unknown. Safety checks exclude other draft revisions, unlinked actions and shadow proposals; full historical refusal and retry coverage is unavailable. This read does not refresh providers.</p>
 </div>;}
export default function DeliveryEvidence({refreshKey=0}:{refreshKey?:number}){
 const evidence=useEvidenceRead<DeliveryEvidenceData>(String(refreshKey));if(!evidence.allowed)return null;
 return <div><button type="button" aria-expanded={evidence.open} onClick={()=>evidence.open?evidence.close():void evidence.load(getDeliveryEvidence)}>{evidence.open?'Hide delivery records':'Inspect delivery records'}</button>{evidence.open&&<div>{evidence.loading&&<p role="status">Loading delivery evidence…</p>}{evidence.error&&<p role="alert">{evidence.error}</p>}{evidence.data&&<DeliveryEvidenceView data={evidence.data}/>}<button type="button" disabled={evidence.loading} onClick={()=>void evidence.load(getDeliveryEvidence)}>Refresh delivery evidence</button></div>}</div>;
}
