import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight} from 'lucide-react';
import {getRecentReplyPage,type ReplyContext,type RecentReply,type RecentRepliesResponse} from '../../../lib/sdrOperationsApi';
import {runLatestRead} from '../../../lib/sdrReadRequest';
import {replyTime,projectLabel,ownerLabel} from './replyDisplay';
import './dashboard.css';
type Destinations={onOpenThread:(target:{threadId:string;mailbox:string})=>void;onOpenProject:(leadId:string)=>void};
export function ReplyDetail({reply,onOpenThread,onOpenProject,onBackToList}:{reply:RecentReply;onBackToList:()=>void}&Destinations) {
 return <article className="sdr-reply-detail" aria-label="Selected reply"><button type="button" className="sdr-reply-button" onClick={onBackToList}><ArrowLeft size={16} aria-hidden="true"/>Back to reply list</button><h2>{reply.prospectEmail||'Recorded human reply'}</h2><p>Incoming {replyTime(reply.receivedAt)}</p><dl><div><dt>Project</dt><dd>{projectLabel(reply)}</dd></div><div><dt>Recorded owner</dt><dd>{ownerLabel(reply)}{reply.owner.status==='verified'&&<small>Routing identity; human follow-through is not established.</small>}</dd></div><div><dt>Last recorded staff touch</dt><dd>{reply.response.status==='recorded'?`${replyTime(reply.response.at)} from ${reply.response.source||'an unknown source'}`:'Needs review · response status unknown'}<small>Staff, other inbox and call responses may be missing.</small></dd></div><div><dt>Deadline</dt><dd>Unknown in this reply feed</dd></div><div><dt>Next action</dt><dd>{reply.response.status==='recorded'?'Not verified':'Review conversation'}</dd></div><div><dt>Recorded source</dt><dd>{reply.source} / {reply.mailbox}</dd></div></dl>
 <div className="sdr-reply-destinations">{reply.threadId?<button className="sdr-reply-button sdr-reply-primary" onClick={()=>onOpenThread({threadId:reply.threadId!,mailbox:reply.mailbox})}>Open conversation <ArrowUpRight size={16} aria-hidden="true"/></button>:<p>Conversation link not recorded.</p>}{reply.project.status==='verified'&&reply.project.id&&<button className="sdr-reply-button" onClick={()=>onOpenProject(reply.project.id!)}>Open project</button>}</div><p className="sdr-reply-destination-note">Open conversation enters the existing inbox and may mark the thread read. Its existing reply controls remain available there.</p>
 <details className="sdr-reply-evidence"><summary>Recorded evidence</summary><p>Project, owner and action evidence is the latest locally recorded evidence; it is not frozen at the reply-window cutoff. Technical receipts do not establish a staff response or a completed follow-up.</p><dl><div><dt>Inbound identity</dt><dd>{reply.id}</dd></div><div><dt>Source message</dt><dd>{reply.sourceMessageId||'Not recorded'}</dd></div><div><dt>Project link basis</dt><dd>{reply.project.basis||'Not recorded'}</dd></div><div><dt>Classification</dt><dd>Human reply{reply.intent?` / ${reply.intent}`:''}</dd></div></dl>{reply.actions.length?<ul>{reply.actions.map((action,index)=><li key={index}>{action.kind.replaceAll('_',' ')}: {action.status.replaceAll('_',' ')}{action.requiresReview?' • Technical review required':''} • {replyTime(action.receiptAt)}</li>)}</ul>:<p>No technical action receipts recorded.</p>}</details>
 </article>;
}
export default function RecentRepliesInbox({context,onBack,onOpenThread,onOpenProject}:{context:ReplyContext;onBack:()=>void}&Destinations) {
 const [data,setData]=useState<RecentRepliesResponse|null>(null),[items,setItems]=useState<RecentReply[]>([]),[selected,setSelected]=useState<string|null>(null),[cursor,setCursor]=useState<string|undefined>(),[reload,setReload]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 const detail=useRef<HTMLDivElement>(null);
 const selectedButton=useRef<HTMLButtonElement|null>(null);
 useEffect(()=>runLatestRead(signal=>getRecentReplyPage(context,cursor,signal),{success:value=>{setData(value);setItems(old=>value.state==='unavailable'?[]:cursor?[...old,...value.items.filter(item=>!old.some(prior=>prior.id===item.id))]:value.items);if(value.state==='unavailable') {setSelected(null);selectedButton.current=null;}setError(false);},error:()=>setError(true),settled:()=>setLoading(false)}),[context,cursor,reload]);
 const reply=items.find(item=>item.id===selected);
 const retry=()=>{setLoading(true);setReload(value=>value+1);};
 return <section className="sdr-replies-browser"><button className="sdr-reply-button" onClick={onBack}><ArrowLeft size={16} aria-hidden="true"/>Back to outreach today</button><header><h1>Recent human replies</h1><p>{replyTime(context.from)} to {replyTime(context.to)} (end excluded)</p><p>{context.mailbox||'Your visible inboxes'} • As of {replyTime(context.asOf)}</p></header>
 {data&&<div className="sdr-reply-coverage"><strong>{data.total===null?'Count unavailable':`${data.total} observed ${data.total===1?'reply':'replies'}; ${items.length} loaded`}</strong><p>{data.coverage.state==='partial'?'Partial inbox coverage':'Inbox coverage unknown'}. {data.coverage.note}</p>{data.coverage.lastCollectedAt&&<p>Last collection: {replyTime(data.coverage.lastCollectedAt)}</p>}</div>}
 {error&&<div role="alert" className="sdr-reply-notice">Replies could not be loaded. {data?'Showing previously loaded records; this view may be stale.':''}<button onClick={retry}>Retry replies</button></div>}
 {loading&&<p role="status">{items.length?'Loading more records…':'Loading recent replies…'}</p>}
 {data?.state==='unavailable'&&<p>Recent reply history is unavailable. The count is unknown.</p>}{data?.state==='available'&&data.total===0&&<p>No human replies recorded in this window. Coverage may be incomplete.</p>}
 <div className="sdr-reply-layout"><div><ul className="sdr-reply-list">{items.map(item=><li key={item.id}><button aria-pressed={selected===item.id} onClick={event=>{selectedButton.current=event.currentTarget;setSelected(item.id);requestAnimationFrame(()=>{detail.current?.focus();detail.current?.scrollIntoView({block:'nearest'});});}}><strong>{item.prospectEmail||projectLabel(item)}</strong><span>{projectLabel(item)}</span><span>{ownerLabel(item)}</span><span>{item.response.status==='recorded'?'Staff response recorded':'Needs review · response status unknown'}</span><time dateTime={item.receivedAt}>{replyTime(item.receivedAt)}</time></button></li>)}</ul>{data?.nextCursor&&<button className="sdr-reply-button" disabled={loading} onClick={()=>{setLoading(true);setCursor(data.nextCursor!);}}>Load more replies</button>}</div><div ref={detail} tabIndex={-1}>{reply?<ReplyDetail key={reply.id} reply={reply} onBackToList={()=>{selectedButton.current?.focus({preventScroll:true});selectedButton.current?.scrollIntoView({block:'center'});}} onOpenThread={onOpenThread} onOpenProject={onOpenProject}/>:items.length>0&&<p className="sdr-reply-select-hint">Select a reply to see its recorded evidence and destinations.</p>}</div></div>
 </section>;
}
